import Head from "next/head";
import styles from "@/styles/pages/Home.module.scss";
import Card from "@/components/Card";
import { mock } from "@/utils/data";
import { CardData } from "@/utils/types/typeCard";
import Navbar from "@/components/Navbar";
import HeroSection from "@/components/HeroSection";
import DropdownList from "@/components/DropdownList";
import { useState, useEffect } from "react";
import Button from "@/components/Button";
import { IoChevronDownCircleOutline } from "react-icons/io5";
import ContentHome from "@/components/ContentHome";
import ContentHomeFiltred from "@/components/ContentHomeFiltred";
import { typeDataSorted } from "@/utils/types/typeDataSorted";
import HeroSection2 from "@/components/HeroSection2";

type PageProps = {
  data: {
    data: CardData[];
  };
  allDeparturePorts: string[];
  sortedData: typeDataSorted[];
};

export default function Home(props: PageProps) {
  // VARIABLES ----------------------
  const stepData = 8;
  // CONDITIONS ---------------------
  const [isFilterActive, setIsFilterActive] = useState<boolean>(false);
  const [dataToShow, setDataToShow] = useState<CardData[]>([]);
  const [specificFilter, setSpecificFilter] = useState<string>("");
  // FUNCTIONS ----------------------
  const handleFilter = (filterValue: string) => {
    if (filterValue !== "All") {
      setIsFilterActive(true);
      setSpecificFilter("");
    } else {
      setIsFilterActive(false);
    }
  };
  const handleSpecificFilter = (valueFilter: string) => {
    valueFilter === "All"
      ? setSpecificFilter("")
      : setSpecificFilter(valueFilter);
  };

  const handleAddMoreContent = () => {
    const auxArray: CardData[] = [...dataToShow];
    let localStep: number;
    if (props.data.data.length - dataToShow.length < stepData) {
      localStep = props.data.data.length - dataToShow.length;
    } else {
      localStep = stepData;
    }

    for (
      let index = dataToShow.length;
      index < localStep + dataToShow.length;
      index++
    ) {
      auxArray.push(props.data.data[index]);
    }
    setDataToShow(auxArray);
  };

  useEffect(() => {
    if (props) {
      handleAddMoreContent();
    }
  }, [props]);
  // VARIABLES ----------------------
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="./assets/images/logo.svg" />
      </Head>
      <main className={`${styles.main}`}>
        <header>
          <Navbar />
        </header>
        <section>
          <HeroSection
            title="Titolo dinamico"
            backgroundImageUrl="https://firebasestorage.googleapis.com/v0/b/meal-hub-3d81b.appspot.com/o/extra%2Fhero.jpeg?alt=media&token=09bef443-8c29-4fc0-acc2-2fe0652e8c59"
          />
        </section>
        {/* ----- */}
        <section className={styles.section__container}>
          <div className={styles.section__content__header}>
            <DropdownList
              values={["Mostra porti di partenza"]}
              name={"Tutti i risultati"}
              callback={(value) => handleFilter(value)}
            />
            {isFilterActive ? (
              <DropdownList
                values={props.allDeparturePorts}
                name="Tutti i porti"
                callback={(value) => handleSpecificFilter(value)}
              />
            ) : null}
          </div>
          <div className={styles.section__content}>
            {isFilterActive ? (
              <ContentHomeFiltred
                filter={specificFilter}
                data={props.sortedData}
              />
            ) : (
              <ContentHome dataToShow={dataToShow} />
            )}
          </div>
          <div className={styles.section__cta}>
            {!isFilterActive && props.data.data.length !== dataToShow.length ? (
              <Button
                width="auto"
                text="MOSTRA ALTRI"
                direction="right"
                onClick={() => handleAddMoreContent()}
                icon={(size) => <IoChevronDownCircleOutline size={size} />}
              />
            ) : null}
          </div>
        </section>
        {/* ------- */}
        <section>
          <HeroSection2
            boxData={[
              {
                counter: "+20",
                title: "Dinamico",
              },
              {
                counter: "+10",
                title: "Dinamico",
              },
              {
                counter: "+3",
                title: "Dinamico",
              },
              {
                counter: "+8",
                title: "Dinamico",
              },
            ]}
          />
        </section>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  let data;
  let allDeparturePorts;
  let sortedData;
  await fetch("http://localhost:3001/api/allDepartues", {
    method: "POST",
    body: "getAllData",
  }).then(async (res) => {
    const alldata = await res.json();
    console.log(alldata.dataSorted);
    data = alldata;
    allDeparturePorts = alldata.allDeparturePorts;
    sortedData = alldata.dataSorted;
  });
  return {
    props: {
      data,
      allDeparturePorts: allDeparturePorts,
      sortedData: sortedData,
    },
  };
}
